// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccountInput struct {
	ID                string                 `json:"id"`
	Name              string                 `json:"name"`
	Email             string                 `json:"email"`
	Phone             string                 `json:"phone"`
	Password          string                 `json:"password"`
	Type              AccountType            `json:"type"`
	VerificationState VerificationState      `json:"verificationState"`
	MessageWallet     *MessagesWalletInput   `json:"messageWallet"`
	OrganizationInfo  *OrganizationInfoInput `json:"organizationInfo"`
	CreatedAt         string                 `json:"createdAt"`
	UpdatedAt         string                 `json:"updatedAt"`
}

type MessagesWalletInput struct {
	ID                      string            `json:"id"`
	Count                   int               `json:"count"`
	Price                   int               `json:"price"`
	SenderID                string            `json:"senderID"`
	SenderVerificationState VerificationState `json:"senderVerificationState"`
	CreatedAt               string            `json:"createdAt"`
	UpdatedAt               string            `json:"updatedAt"`
}

type OrganizationInfoInput struct {
	ID            string               `json:"id"`
	Name          string               `json:"name"`
	Phone         string               `json:"phone"`
	MessageWallet *MessagesWalletInput `json:"messageWallet"`
}
