type MessagesWallet {
    id: ID!
    count: Int!
    price: Int!
    senderID: String!
    senderVerificationState: VerificationState!
    createdAt: Datetime!
    updatedAt: Datetime!
}
input MessagesWalletInput {
    id: ID!
    count: Int!
    price: Int!
    senderID: String!
    senderVerificationState: VerificationState!
    createdAt: Datetime!
    updatedAt: Datetime!
}